export interface WorkedOn {
  project: string;
  url: string;
}

interface Exp {
  year: string;
  company: string;
  role: string;
  contributions: string[];
  techStack: string[];
  projects?: WorkedOn[];
}

export const experience: Exp[] = [
  {
    role: `Lead React native developer`,
    company: "Connect up",
    year: "2024-To date",
    projects: [
      {
        project: "Connect up",
        url: "https://play.google.com/store/search?q=connect+up&c=apps",
      },
    ],
    contributions: [
      "Reduced app load time by 40% through code optimization and reducing re-renders",
      "Enhanced retention by 15% with smoother navigation, offline support, and real-time notifications",
      "Decreased memory usage by 25% via image optimization and native video processing modules",
      "Led migration from React Native 0.59 to 0.75, ensuring 100% compatibility and smooth transitions",
      "Lowered crash rates by 30% with proactive error handling and memory leak detection",
      "Mentored a team of 5 developers, increasing project delivery speed by 20%",
      "Improved usability in low-connectivity environments, increasing user satisfaction by 18%",
    ],
    techStack: [
      "/assets/typescript.svg",
      "/assets/figma.png",
      "/assets/firebase.svg",
      "/assets/react.svg",
      "/assets/redux.svg",
      "/assets/docker.svg",
      "/assets/git.svg",
      "/assets/php.svg",
      "/assets/Android Studio.svg",
      "/assets/CMake.svg",
      "/assets/Google Cloud.svg",
      "/assets/Kotlin.svg",
      "/assets/kubernetes.svg",
      "/assets/MySQL.svg",
      "/assets/Swift.svg",
      "/assets/Visual Studio Code.svg",
    ],
  },
  {
    role: `Fullstack Engineer`,
    company: "Aerial Inc",
    year: "2023-To 2024",
    projects: [{ project: "Aerial app", url: "https://aerialops.io/" }],
    contributions: [
      "Improved frontend UX by integrating APIs, applying code splitting, and reducing complaints by 10%",
      "Developed document processing tools using pdfjs-dist, jszip, and machine learning for authenticity verification",
      "Co-developed ts-mongo for type-safe MongoDB interactions, increasing code reusability",
      "Automated CI/CD pipelines with GitHub Actions, cutting manual tasks by 40%",
      "Participating in code reviews and providing constructive feedback to other developers",
    ],
    techStack: [
      "/assets/typescript.svg",
      "/assets/react.svg",
      "/assets/nextjs.svg",
      "/assets/docker.svg",
      "/assets/Cypress.svg",
      "/assets/GraphQL.svg",
      "/assets/sass.svg",
      "/assets/css.svg",
      "/assets/Storybook.svg",
      "/assets/Webpack.svg",
      "/assets/AWS.svg",
      "/assets/Redis.svg",
      "/assets/GitHub Actions.svg",
      "/assets/Visual Studio Code.svg",
      "/assets/firebase.svg",
      "/assets/MaterialUI.svg",
      "/assets/mongodb.svg",
      "/assets/JSON.svg",
      "/assets/Vercel.svg",
    ],
  },
  {
    role: `Full stack team lead developer`,
    company: "GitStart YC(S-19)",
    year: "2020-To 2023",
    contributions: [
      "Led migration from enzyme to React Testing Library, securing a 3-year client extension",
      "Developed a component library reducing dependencies and improving page load by 20%",
      "Automated CI/CD pipeline with GitHub Actions, boosting delivery efficiency by 30%",
      "Mentored a team of 8 developers, increasing project delivery speed by 20%",
    ],
    projects: [
      { project: "Company website,", url: "https://www.gitstart.com/" },
      { project: "Developer portal,", url: "https://www.gitstart.dev/" },
      { project: "Sourcegraph,", url: "https://about.sourcegraph.com/" },
      { project: "Superbase,", url: "https://supabase.com/" },
      { project: "Cypress", url: "https://www.cypress.io/" },
    ],
    techStack: [
      "/assets/typescript.svg",
      "/assets/react.svg",
      "/assets/express.svg",
      "/assets/nodejs.svg",
      "/assets/docker.svg",
      "/assets/kubernetes.svg",
      "/assets/Cypress.svg",
      "/assets/AWS.svg",
      "/assets/GraphQL.svg",
      "/assets/sass.svg",
      "/assets/css.svg",
      "/assets/Storybook.svg",
      "/assets/Webpack.svg",
      "/assets/Go.svg",
      "/assets/Bash.svg",
      "/assets/Redis.svg",
      "/assets/GitHub Actions.svg",
      "/assets/Visual Studio Code.svg",
      "/assets/PostgresSQL.svg",
      "/assets/firebase.svg",
    ],
  },
  {
    role: `Full stack software Engineer at Netbritz.com`,
    company: "Netbritz",
    year: "2018-To 2020",
    projects: [{ project: "Company website", url: "https://netbritz.com/" }],
    contributions: [
      "Rewrote server code from PHP to Node.js, increasing site speed by 15%",
      "Enhanced CI/CD pipelines and optimized database queries, improving performance by 12%.",
      "Implementing responsive design and ensuring cross-browser compatibility",
    ],
    techStack: [
      "/assets/typescript.svg",
      "/assets/react.svg",
      "/assets/docker.svg",
      "/assets/express.svg",
      "/assets/nodejs.svg",
      "/assets/kubernetes.svg",
      "/assets/Cypress.svg",
      "/assets/redux.svg",
      "/assets/GraphQL.svg",
      "/assets/sass.svg",
      "/assets/css.svg",
      "/assets/Storybook.svg",
      "/assets/Webpack.svg",
      "/assets/AWS.svg",
      "/assets/nextjs.svg",
      "/assets/PostgresSQL.svg",
      "/assets/nextjs.svg",
      "/assets/firebase.svg",
      "/assets/D3.js.svg",
      "/assets/GitHub Actions.svg",
      "/assets/Visual Studio Code.svg",
    ],
  },
  {
    role: `Fullstack team leader developer`,
    company: "Wakanda Great View Holidays",
    year: "2017-2018",
    contributions: [
      "Improved UI, resulting in a 20% drop in user complaints and a 40% traffic boost via SEO enhancements",
      "Led migration to cloud hosting, improving performance and traffic by 30%",
      "Implementing responsive design and ensuring cross-browser compatibility",
      "Participating in code reviews and providing constructive feedback to other developers",
    ],
    techStack: [
      "/assets/javascript.svg",
      "/assets/php.svg",
      "/assets/Laravel.svg",
      "/assets/AWS.svg",
      "/assets/PostgresSQL.svg",
      "/assets/html.svg",
      "/assets/sass.svg",
      "/assets/css.svg",
      "/assets/docker.svg",
      "/assets/MaterialUI.svg",
    ],
  },
];
